apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cloudnautic
data:
  FLASK_ENV: "production"
  PORT: "5000"
  JWT_SECRET_KEY: "production-jwt-secret-change-me"
  SECRET_KEY: "production-secret-key-change-me"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: cloudnautic
data:
  REACT_APP_API_URL: "http://backend-svc:5000/api"
  REACT_APP_VERSION: "1.0.0"
  REACT_APP_NAME: "Cloudnautic Shop"